# Generated by Django 3.1.2 on 2021-06-01 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0003_auto_20210601_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=255, storage=file.storage.UserDataFileStorage(), upload_to=file.storage.create_file_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
    ]
