# Generated by Django 3.1.2 on 2021-06-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_auto_20210604_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmodel',
            name='subject',
        ),
        migrations.AddField(
            model_name='mailmodel',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailmodel',
            name='template',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
