# Generated by Django 3.1.2 on 2021-06-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_auto_20210607_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailmodel',
            options={'verbose_name': 'Mail message'},
        ),
    ]
