# Generated by Django 3.1.2 on 2021-03-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210319_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
