# Generated by Django 3.1.2 on 2021-03-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210319_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='main',
            new_name='primary',
        ),
        migrations.RenameField(
            model_name='emailaddress',
            old_name='main',
            new_name='primary',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='main',
            new_name='primary',
        ),
    ]
