# Generated by Django 3.1.2 on 2021-06-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210330_1214'),
        ('user', '0007_auto_20210325_0936'),
    ]

    operations = [
    ]
