# Generated by Django 3.1.2 on 2021-06-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_merge_20210604_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='email_address',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
