# Generated by Django 3.1.2 on 2021-06-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_emailtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
