# Generated by Django 3.1.2 on 2021-06-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210610_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='user',
            name='ban_reason',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
