# Generated by Django 3.1.2 on 2021-06-11 12:59

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210610_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.CharField(default=user.models.generate_token, max_length=6),
        ),
    ]
