# Generated by Django 3.1.2 on 2021-08-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210611_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_email_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_phone_code_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_phone_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
