# Generated by Django 3.1.2 on 2021-08-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20210818_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='last_email_code_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
