# Generated by Django 3.1.2 on 2021-08-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210819_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtoken',
            old_name='email_address',
            new_name='email_object',
        ),
        migrations.AddField(
            model_name='emailtoken',
            name='email_address',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
