# Generated by Django 3.1.2 on 2021-08-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_systemmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTokenSpamBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(blank=True, max_length=320, null=True)),
                ('last_email_code_request', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_email_code_request',
        ),
    ]
